import 'package:lebs/intl/tran_intl.dart';

Map<String, String> en = {
  Intl.home: "Home",
  Intl.schedule: "Schedule",
  Intl.history: "History",
  Intl.discovery: "Discovery",
  Intl.me: "Me",
  Intl.login: "Login",
  Intl.addStudent: "Add Student",
  Intl.studentProfile: "Student Profile",
  Intl.completedClasses: "Completed Classes",
  Intl.missedClasses: "Missed Classes",
  Intl.preview: "Preview",
  Intl.classSummary: "Class Summary",
  Intl.review: "Review",
  Intl.playback: "Playback",
  Intl.assignment: "Assignment",
  Intl.account: "Account",
  Intl.addClasses: "Add Classes",
  Intl.coupon: "Coupon",
  Intl.order: "Order",
  Intl.faq: "FAQ",
  Intl.feedback: "Feedback",
  Intl.setting: "Setting",
  Intl.itTest: "ItTest",
  Intl.language: "Language",
  Intl.recording: "Student Recording",
  Intl.version: "Version",
  Intl.conditions: "Terms and Conditions",
  Intl.deleteAccount: "Delete Account",
  Intl.signOut: "Sign Out",
  Intl.chooseLanguage: "Choose Language",
  Intl.cancel: "Cancel",
};
