import 'package:lebs/intl/tran_intl.dart';

Map<String, String> zh_CN = {
  Intl.home: "主页",
  Intl.schedule: "课表",
  Intl.history: "历史课程",
  Intl.discovery: "发现",
  Intl.me: "我的",
  Intl.login: "登录",
  Intl.addStudent: "添加学生",
  Intl.studentProfile: "学生信息",
  Intl.completedClasses: "已完成",
  Intl.missedClasses: "异常",
  Intl.preview: "预习",
  Intl.classSummary: "本课小结",
  Intl.review: "复习",
  Intl.playback: "回放",
  Intl.assignment: "课后巩固",
  Intl.account: "账户",
  Intl.addClasses: "充值",
  Intl.coupon: "优惠券",
  Intl.order: "订单",
  Intl.faq: "常见问题",
  Intl.feedback: "用户反馈",
  Intl.setting: "设置",
  Intl.itTest: "设备检测",
  Intl.language: "语言",
  Intl.recording: "录制设置",
  Intl.version: "版本",
  Intl.conditions: "协议",
  Intl.deleteAccount: "删除账号",
  Intl.signOut: "退出登录",
  Intl.chooseLanguage: "选择语言",
  Intl.cancel: "取消"
};
